#:kivy 2.1.0

<Text>:
    size: label.size

    BetterSizedLabel:
        id: label
        size_hint: None, None

        text: root.storage.text
        font_size: root.storage.font_size
        do_markup: root.storage.do_markup


<ScoreSection>:
    canvas:
        Color:
            rgba: 0, 1, 0, 0#.2
        Rectangle:
            size: self.size

<PageContent>:  # No content will even need this
    size_hint: None, None